async function fetchActuals() {
  // Example of 실적 DB rows with Month in 'YYYY-MM' format
  // For a real app, return many months for each Site/Oper
  return [
    {
      Month: "2025-07",
      Area: "A",
      Site: "S1",
      Oper: "O1",
      target: "Y",
      factor1: 86,
      factor2: 9,
      factor3: 6,
    },
    {
      Month: "2025-06",
      Area: "A",
      Site: "S1",
      Oper: "O1",
      target: "Y",
      factor1: 84,
      factor2: 11,
      factor3: 5,
    },
    {
      Month: "2025-05",
      Area: "A",
      Site: "S1",
      Oper: "O1",
      target: "Y",
      factor1: 83,
      factor2: 12,
      factor3: 5,
    },
    {
      Month: "2025-04",
      Area: "A",
      Site: "S1",
      Oper: "O1",
      target: "Y",
      factor1: 82,
      factor2: 14,
      factor3: 7,
    },

    {
      Month: "2025-07",
      Area: "A",
      Site: "S2",
      Oper: "O2",
      target: "Y",
      factor1: 78,
      factor2: 13,
      factor3: 6,
    },
    {
      Month: "2025-06",
      Area: "A",
      Site: "S2",
      Oper: "O2",
      target: "Y",
      factor1: 79,
      factor2: 12,
      factor3: 6,
    },
    {
      Month: "2025-05",
      Area: "A",
      Site: "S2",
      Oper: "O2",
      target: "Y",
      factor1: 81,
      factor2: 11,
      factor3: 5,
    },

    {
      Month: "2025-07",
      Area: "B",
      Site: "S3",
      Oper: "O3",
      target: "Y",
      factor1: 91,
      factor2: 7,
      factor3: 3,
    },
    {
      Month: "2025-06",
      Area: "B",
      Site: "S3",
      Oper: "O3",
      target: "Y",
      factor1: 92,
      factor2: 6,
      factor3: 4,
    },
    {
      Month: "2025-05",
      Area: "B",
      Site: "S3",
      Oper: "O3",
      target: "Y",
      factor1: 89,
      factor2: 9,
      factor3: 4,
    },
  ];
}

export default fetchActuals;
